Configuration:
  name: Default 
  Properties:
    Property:
      name: log-path
      value: "logs"
  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
    RollingRandomAccessFile:
      - name: Async_File_Appender
        fileName: ${log-path}/app.log
        filePattern: ${log-path}/app-%d{yyyy-MM-dd-HH-mm-ss-SSS}.log
        immediateFlush: false
        append: true
        PatternLayout:
          pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
        Policies:
          OnStartupTriggeringPolicy: {} 
          SizeBasedTriggeringPolicy:
            size: 10 MB
        DefaultRollOverStrategy:
          max: 50
      - name: CSV
        fileName: ${log-path}/telemetry.csv
        filePattern: ${log-path}/telemetry-%d{yyyy-MM-dd-HH-mm-ss-SSS}.csv
        immediateFlush: false
        append: true
        CsvParameterLayout:
          delimiter: ","   
        Policies:
          OnStartupTriggeringPolicy: {}
          SizeBasedTriggeringPolicy:
            size: 10 MB
        DefaultRollOverStrategy:
          max: 50
      - name: PERF_TIMER_LOG
        fileName: ${log-path}/perftimes.csv
        filePattern: ${log-path}/perftimes-%d{yyyy-MM-dd-HH-mm-ss-SSS}.csv
        immediateFlush: true
        append: true
        CsvParameterLayout:
          delimiter: ","
          header: "Robot Start, Offset Time, Name, Count, Mean, Std Dev, Total Time, Median, 75th Percentile, 95 Percentile, 99th Percentile\n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 1 MB
        DefaultRollOverStrategy:
          max: 50
  Loggers:
      Root:
        level: info
        AppenderRef:
          - ref: Console_Appender
            level: info
          - ref: Async_File_Appender
            level: debug
      Logger:
        - name: TELEMETRY
          level: debug
          AppenderRef:
            - ref: CSV
              level: debug
            - ref: Async_File_Appender
              level: debug
        - name: PERF_TIMERS
          level: trace
          AppenderRef:
            - ref: PERF_TIMER_LOG
        - name: frc.robot.gamepieces.LoggingPerfTest
          level: info
          AppenderRef:
            - ref: Console_Appender
        - name: frc.robot.drive.SparkMaxSpeedControllerGroup
          level: info
          AppenderRef:
            - ref: Async_File_Appender