Configuration:
  name: Default
 
  Properties:
    Property:
      name: log-path
      value: "logs"
 
  Appenders:
 
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
 
    File:
      name: File_Appender
      fileName: ${log-path}/logfile.log
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
 
  Loggers:
 
      Root:
        level: info
        AppenderRef:
          - ref: Console_Appender
 
      # Create override loggers per class
      Logger:
        - name: frc.robot.Robot
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.CargoIntake
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.CargoMech
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.GamePieceBase
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.GamePieceController
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.GamePieceControllerTest
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.HatchMechanism
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
        - name: frc.robot.gamepieces.Turret
          level: debug
          AppenderRef:
            - ref: File_Appender
              level: info
