Configuration:
  name: Default
 
  Properties:
    Property:
      name: log-path
      value: "logs"
 
  Appenders:
 
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
 
    File:
      name: File_Appender
      fileName: ${log-path}/logfile.log
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
 
  Loggers:
 
      Root:
        level: error
      AppenderRef:
        - ref: Console_Appender